apiVersion: v1
kind: Service
metadata:
  name: vprodb #from application.properties file
spec:
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP